#!/usr/bin/env python
from __future__ import annotations

import argparse
import copy
import json
import math
import os
import random
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, MutableMapping, Sequence

import numpy as np


MODEL_CANDIDATES: Dict[str, Dict[str, str]] = {
    "dynamic_rcnn_r50_fpn_1x": {
        "config_rel_path": "dynamic_rcnn/dynamic-rcnn_r50_fpn_1x_coco.py",
        "paper": "https://arxiv.org/abs/2004.06002",
        "repo": "https://github.com/open-mmlab/mmdetection/tree/main/configs/dynamic_rcnn",
    },
    "cascade_rcnn_r50_fpn_1x": {
        "config_rel_path": "cascade_rcnn/cascade-rcnn_r50_fpn_1x_coco.py",
        "paper": "https://arxiv.org/abs/1906.09756",
        "repo": "https://github.com/open-mmlab/mmdetection/tree/main/configs/cascade_rcnn",
    },
    "libra_faster_rcnn_r50_fpn_1x": {
        "config_rel_path": "libra_rcnn/libra-faster-rcnn_r50_fpn_1x_coco.py",
        "paper": "https://arxiv.org/abs/1904.02701",
        "repo": "https://github.com/open-mmlab/mmdetection/tree/main/configs/libra_rcnn",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train RCNN-family detectors with MMDetection on PET tiled COCO dataset.\n"
            "Designed to reuse the same preprocessing output from prepare_tiled_coco_dataset.py."
        )
    )
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        default=Path("data") / "rcnn_tiled_coco",
        help="COCO root containing train/valid/test and _annotations.coco.json.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("runs") / "dynamic-rcnn-r50",
        help="Training output directory (work_dir).",
    )
    parser.add_argument(
        "--model",
        choices=sorted(MODEL_CANDIDATES.keys()),
        default="dynamic_rcnn_r50_fpn_1x",
        help="RCNN-family model preset (recommended default: dynamic_rcnn_r50_fpn_1x).",
    )
    parser.add_argument(
        "--base-config",
        type=str,
        default=None,
        help=(
            "Optional config file path override. "
            "If omitted, uses the preset config_rel_path from installed mmdet package."
        ),
    )
    parser.add_argument("--epochs", type=int, default=36)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--val-batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=8)
    parser.add_argument(
        "--lr",
        type=float,
        default=0.005,
        help="Learning rate (set None to keep base config value).",
    )
    parser.add_argument("--image-size", type=int, default=256)
    parser.add_argument(
        "--anchor-scales",
        type=int,
        nargs="+",
        default=[2, 4, 8],
        help="RPN anchor scales for small-defect sensitivity.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--disable-augment",
        action="store_true",
        help="Disable RF-DETR-style color/illumination augmentations.",
    )
    parser.add_argument(
        "--include-classes",
        nargs="+",
        default=None,
        help="Train only selected class names (space/comma separated).",
    )
    parser.add_argument(
        "--exclude-classes",
        nargs="+",
        default=["unknown"],
        help="Exclude class names from training (space/comma separated).",
    )
    parser.add_argument(
        "--amp",
        action="store_true",
        help="Enable mixed precision via AmpOptimWrapper.",
    )
    parser.add_argument(
        "--load-from",
        type=str,
        default=None,
        help="Checkpoint path or URL for weight initialization.",
    )
    parser.add_argument(
        "--resume-from",
        type=Path,
        default=None,
        help="Resume training from checkpoint path.",
    )
    parser.add_argument(
        "--test-after-train",
        action="store_true",
        help="Run test split evaluation immediately after training.",
    )
    parser.add_argument(
        "--test-only",
        action="store_true",
        help="Skip training and run test/eval only (requires --load-from or --resume-from).",
    )
    parser.add_argument("--max-keep-ckpts", type=int, default=3)
    parser.add_argument(
        "--save-best-metric",
        type=str,
        default="coco/bbox_mAP_class_mean",
        help=(
            "Metric key used by CheckpointHook.save_best. "
            "Default uses class-wise mean AP generated by custom CocoMetric."
        ),
    )
    parser.add_argument(
        "--class-mean-exclude",
        nargs="+",
        default=None,
        help=(
            "Class names excluded when computing bbox_mAP_class_mean "
            "(space/comma separated)."
        ),
    )
    parser.add_argument(
        "--gpu-id",
        type=int,
        default=None,
        help=(
            "Use a specific GPU index (e.g., 0/1/2). "
            "If omitted, the script auto-selects the least-loaded GPU."
        ),
    )
    parser.add_argument(
        "--exclude-gpus",
        type=int,
        nargs="*",
        default=[],
        help="GPU indices to exclude from auto selection.",
    )
    parser.add_argument(
        "--overwrite-filtered",
        action="store_true",
        help="Overwrite output_dir/_filtered_dataset if class filtering is used.",
    )
    return parser.parse_args()


def parse_class_tokens(raw_values: Sequence[str] | None) -> List[str]:
    if not raw_values:
        return []
    out: List[str] = []
    seen = set()
    for raw in raw_values:
        for token in str(raw).split(","):
            name = token.strip()
            if not name:
                continue
            key = name.lower()
            if key in seen:
                continue
            seen.add(key)
            out.append(name)
    return out


def ensure_dataset_layout(dataset_dir: Path) -> None:
    required = [
        dataset_dir / "train" / "_annotations.coco.json",
        dataset_dir / "valid" / "_annotations.coco.json",
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        joined = "\n".join(missing)
        raise FileNotFoundError(
            "Dataset layout is incomplete. Missing:\n"
            f"{joined}\n"
            "Run scripts/prepare_tiled_coco_dataset.py first."
        )


def load_coco_categories(ann_path: Path) -> List[Dict[str, Any]]:
    payload = json.loads(ann_path.read_text(encoding="utf-8"))
    categories = payload.get("categories", [])
    if not categories:
        raise ValueError(f"No categories found in {ann_path}")
    categories = sorted(categories, key=lambda x: int(x["id"]))
    return categories


def summarize_split(dataset_dir: Path, split: str) -> str:
    ann_path = dataset_dir / split / "_annotations.coco.json"
    if not ann_path.exists():
        return f"{split}: not found"
    payload = json.loads(ann_path.read_text(encoding="utf-8"))
    return (
        f"{split}: images={len(payload.get('images', []))}, "
        f"annotations={len(payload.get('annotations', []))}, "
        f"categories={len(payload.get('categories', []))}"
    )


def resolve_selected_class_names(
    all_class_names: Sequence[str],
    include_tokens: Sequence[str],
    exclude_tokens: Sequence[str],
) -> List[str]:
    lowered_to_name = {name.lower(): name for name in all_class_names}

    missing_include = [n for n in include_tokens if n.lower() not in lowered_to_name]
    if missing_include:
        raise ValueError(
            "Unknown class name(s) in --include-classes: " + ", ".join(missing_include)
        )

    missing_exclude = [n for n in exclude_tokens if n.lower() not in lowered_to_name]
    if missing_exclude:
        print(
            "Warning: unknown class name(s) in --exclude-classes ignored: "
            + ", ".join(missing_exclude)
        )

    if include_tokens:
        selected = [lowered_to_name[n.lower()] for n in include_tokens]
    else:
        selected = list(all_class_names)

    excluded = {n.lower() for n in exclude_tokens}
    selected = [name for name in selected if name.lower() not in excluded]
    if not selected:
        raise ValueError("No classes left after include/exclude filtering.")
    return selected


def build_filtered_dataset(
    source_dataset_dir: Path,
    filtered_dataset_dir: Path,
    selected_class_names: Sequence[str],
    overwrite: bool,
) -> Path:
    if filtered_dataset_dir.exists():
        if not overwrite:
            raise FileExistsError(
                f"{filtered_dataset_dir} already exists. Use --overwrite-filtered to recreate."
            )
        shutil.rmtree(filtered_dataset_dir)
    filtered_dataset_dir.mkdir(parents=True, exist_ok=True)

    selected_set = set(selected_class_names)
    name_to_new_id = {name: idx + 1 for idx, name in enumerate(selected_class_names)}
    global_categories = [
        {"id": idx + 1, "name": name, "supercategory": "defect"}
        for idx, name in enumerate(selected_class_names)
    ]

    for split in ("train", "valid", "test"):
        src_ann = source_dataset_dir / split / "_annotations.coco.json"
        if not src_ann.exists():
            continue

        payload = json.loads(src_ann.read_text(encoding="utf-8"))
        src_split_dir = source_dataset_dir / split
        old_id_to_name = {
            int(cat["id"]): str(cat["name"]) for cat in payload.get("categories", [])
        }
        old_id_to_new_id = {
            old_id: name_to_new_id[name]
            for old_id, name in old_id_to_name.items()
            if name in selected_set
        }

        filtered_images = []
        for img in payload.get("images", []):
            new_img = copy.deepcopy(img)
            raw_name = str(new_img.get("file_name", "")).strip()
            if not raw_name:
                continue
            raw_path = Path(raw_name)
            if raw_path.is_absolute():
                abs_img_path = raw_path
            else:
                abs_img_path = (src_split_dir / raw_name).resolve()
            new_img["file_name"] = str(abs_img_path)
            filtered_images.append(new_img)

        filtered_annotations = []
        for ann in payload.get("annotations", []):
            old_cat_id = int(ann.get("category_id", -1))
            if old_cat_id not in old_id_to_new_id:
                continue
            new_ann = copy.deepcopy(ann)
            new_ann["category_id"] = old_id_to_new_id[old_cat_id]
            filtered_annotations.append(new_ann)

        filtered_payload = copy.deepcopy(payload)
        filtered_payload["images"] = filtered_images
        filtered_payload["categories"] = global_categories
        filtered_payload["annotations"] = filtered_annotations

        dst_split_dir = filtered_dataset_dir / split
        dst_split_dir.mkdir(parents=True, exist_ok=True)
        (dst_split_dir / "_annotations.coco.json").write_text(
            json.dumps(filtered_payload, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    return filtered_dataset_dir


def prepare_dataset_for_class_selection(
    source_dataset_dir: Path,
    output_dir: Path,
    include_tokens: Sequence[str],
    exclude_tokens: Sequence[str],
    overwrite_filtered: bool,
) -> tuple[Path, List[str]]:
    categories = load_coco_categories(source_dataset_dir / "train" / "_annotations.coco.json")
    all_class_names = [str(c["name"]) for c in categories]
    selected_class_names = resolve_selected_class_names(
        all_class_names=all_class_names,
        include_tokens=include_tokens,
        exclude_tokens=exclude_tokens,
    )

    selection_meta = {
        "source_dataset_dir": str(source_dataset_dir),
        "all_class_names": all_class_names,
        "selected_class_names": selected_class_names,
        "include_classes": list(include_tokens),
        "exclude_classes": list(exclude_tokens),
    }

    if selected_class_names == all_class_names:
        selection_meta["filtered_dataset_dir"] = None
        (output_dir / "class_selection.json").write_text(
            json.dumps(selection_meta, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        return source_dataset_dir, selected_class_names

    filtered_dataset_dir = output_dir / "_filtered_dataset"
    filtered_dataset_dir = build_filtered_dataset(
        source_dataset_dir=source_dataset_dir,
        filtered_dataset_dir=filtered_dataset_dir,
        selected_class_names=selected_class_names,
        overwrite=overwrite_filtered,
    )
    selection_meta["filtered_dataset_dir"] = str(filtered_dataset_dir)
    (output_dir / "class_selection.json").write_text(
        json.dumps(selection_meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return filtered_dataset_dir, selected_class_names


def unwrap_dataset_cfg(dataset_cfg: MutableMapping[str, Any]) -> MutableMapping[str, Any]:
    cur = dataset_cfg
    while isinstance(cur, MutableMapping) and "dataset" in cur:
        next_cfg = cur.get("dataset")
        if not isinstance(next_cfg, MutableMapping):
            break
        cur = next_cfg
    return cur


def set_dataset_cfg(
    cfg: MutableMapping[str, Any],
    ann_file: Path,
    img_dir: Path,
    classes: Sequence[str],
    is_train: bool,
    image_size: int,
    use_augment: bool,
    albu_transforms: List[Dict[str, Any]] | None,
) -> None:
    dataset_cfg = unwrap_dataset_cfg(cfg)
    dataset_cfg["type"] = "CocoDataset"
    dataset_cfg["ann_file"] = str(ann_file.resolve())
    dataset_cfg["data_prefix"] = {"img": str(img_dir.resolve()) + os.sep}
    dataset_cfg["metainfo"] = {"classes": tuple(classes)}
    if is_train:
        dataset_cfg["filter_cfg"] = {"filter_empty_gt": False, "min_size": 1}

    if is_train:
        train_pipeline: List[Dict[str, Any]] = [
            {"type": "LoadImageFromFile"},
            {"type": "LoadAnnotations", "with_bbox": True},
            {"type": "Resize", "scale": (image_size, image_size), "keep_ratio": False},
        ]
        if use_augment and albu_transforms:
            train_pipeline.append(
                {
                    "type": "Albu",
                    "transforms": albu_transforms,
                    "bbox_params": {
                        "type": "BboxParams",
                        "format": "pascal_voc",
                        "label_fields": ["gt_bboxes_labels"],
                        "min_visibility": 0.0,
                        "filter_lost_elements": False,
                    },
                    "keymap": {"img": "image", "gt_bboxes": "bboxes"},
                    "skip_img_without_anno": False,
                }
            )
        else:
            train_pipeline.append({"type": "RandomFlip", "prob": 0.5})
        train_pipeline.append({"type": "PackDetInputs"})
        dataset_cfg["pipeline"] = train_pipeline
    else:
        dataset_cfg["pipeline"] = [
            {"type": "LoadImageFromFile"},
            {"type": "Resize", "scale": (image_size, image_size), "keep_ratio": False},
            {"type": "LoadAnnotations", "with_bbox": True},
            {
                "type": "PackDetInputs",
                "meta_keys": (
                    "img_id",
                    "img_path",
                    "ori_shape",
                    "img_shape",
                    "scale_factor",
                ),
            },
        ]


def build_rfdetr_style_albu_transforms() -> List[Dict[str, Any]]:
    """
    Match RF-DETR train_rfdetr.py augmentation policy:
    - HorizontalFlip p=0.2
    - OneOf color/illumination transforms with weighted child p
    """
    return [
        {"type": "HorizontalFlip", "p": 0.2},
        {
            "type": "OneOf",
            "p": 1.0,
            "transforms": [
                {
                    "type": "RandomBrightnessContrast",
                    "brightness_limit": 0.35,
                    "contrast_limit": 0.35,
                    "p": 0.22,
                },
                {
                    "type": "ColorJitter",
                    "brightness": 0.35,
                    "contrast": 0.35,
                    "saturation": 0.30,
                    "hue": 0.06,
                    "p": 0.20,
                },
                {
                    "type": "HueSaturationValue",
                    "hue_shift_limit": 15,
                    "sat_shift_limit": 35,
                    "val_shift_limit": 35,
                    "p": 0.18,
                },
                {
                    "type": "RGBShift",
                    "r_shift_limit": 30,
                    "g_shift_limit": 30,
                    "b_shift_limit": 30,
                    "p": 0.15,
                },
                {"type": "RandomGamma", "gamma_limit": [70, 140], "p": 0.12},
                {
                    "type": "CLAHE",
                    "clip_limit": [1, 4],
                    "tile_grid_size": [8, 8],
                    "p": 0.08,
                },
                {"type": "ChannelShuffle", "p": 0.05},
                {"type": "NoOp", "p": 0.15},
            ],
        },
    ]


def recursively_set_num_classes(node: Any, num_classes: int) -> int:
    updated = 0
    if isinstance(node, MutableMapping):
        for key, value in list(node.items()):
            if key == "num_classes" and isinstance(value, int) and value > 0:
                node[key] = num_classes
                updated += 1
            updated += recursively_set_num_classes(value, num_classes)
    elif isinstance(node, list):
        for item in node:
            updated += recursively_set_num_classes(item, num_classes)
    return updated


def set_small_object_anchor_scales(model_cfg: MutableMapping[str, Any], scales: Sequence[int]) -> bool:
    rpn_head = model_cfg.get("rpn_head")
    if not isinstance(rpn_head, MutableMapping):
        return False
    anchor_generator = rpn_head.get("anchor_generator")
    if not isinstance(anchor_generator, MutableMapping):
        return False
    anchor_generator["scales"] = list(scales)
    anchor_generator.pop("octave_base_scale", None)
    anchor_generator.pop("scales_per_octave", None)
    return True


def rescale_schedule(cfg: MutableMapping[str, Any], target_epochs: int) -> None:
    train_cfg = cfg.get("train_cfg", {})
    if not isinstance(train_cfg, MutableMapping):
        return
    original_max_epochs = int(train_cfg.get("max_epochs", target_epochs))
    train_cfg["max_epochs"] = int(target_epochs)
    train_cfg["val_interval"] = 1

    schedulers = cfg.get("param_scheduler", None)
    if not isinstance(schedulers, list):
        return

    for sch in schedulers:
        if not isinstance(sch, MutableMapping):
            continue
        if "milestones" in sch and isinstance(sch["milestones"], list):
            new_milestones = []
            for m in sch["milestones"]:
                scaled = int(round(float(m) / max(1, original_max_epochs) * target_epochs))
                scaled = max(1, min(target_epochs - 1, scaled))
                new_milestones.append(scaled)
            sch["milestones"] = sorted(set(new_milestones))
        if "end" in sch and isinstance(sch["end"], int) and sch["end"] == original_max_epochs:
            sch["end"] = int(target_epochs)


def find_mmdet_config_from_installed_package(rel_path: str) -> Path:
    import mmdet  # type: ignore

    mmdet_pkg_dir = Path(mmdet.__file__).resolve().parent
    candidates = [
        mmdet_pkg_dir / ".mim" / "configs" / rel_path,
        mmdet_pkg_dir.parent / ".mim" / "configs" / rel_path,
        mmdet_pkg_dir.parents[1] / ".mim" / "configs" / rel_path,
    ]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        f"Could not find config '{rel_path}' in installed mmdet package.\n"
        "Please check your mmdet installation or pass --base-config explicitly."
    )


def resolve_checkpoint_for_test(args: argparse.Namespace, output_dir: Path) -> str:
    if args.resume_from is not None:
        return str(args.resume_from.resolve())
    if args.load_from:
        return args.load_from
    latest = output_dir / "latest.pth"
    if latest.exists():
        return str(latest.resolve())
    best = sorted(output_dir.glob("best_*.pth"))
    if best:
        return str(best[-1].resolve())
    raise FileNotFoundError(
        "No checkpoint found for testing. Provide --load-from or --resume-from."
    )


def _register_coco_metric_with_class_mean() -> None:
    from mmdet.evaluation.metrics import CocoMetric
    from mmdet.registry import METRICS

    @METRICS.register_module(force=True)
    class CocoMetricWithClassMean(CocoMetric):  # type: ignore[misc]
        """
        Extend CocoMetric to expose class-wise mean AP as `bbox_mAP_class_mean`.
        This metric is computed from per-class `*_precision` values (AP over IoU 0.5:0.95).
        """

        def __init__(self, class_mean_exclude: Sequence[str] | None = None, **kwargs) -> None:
            kwargs.setdefault("classwise", True)
            super().__init__(**kwargs)
            self.class_mean_exclude = {str(x).strip().lower() for x in (class_mean_exclude or []) if str(x).strip()}

        def compute_metrics(self, results: list) -> Dict[str, float]:
            eval_results = super().compute_metrics(results)
            class_scores: List[float] = []

            for key, value in eval_results.items():
                if not key.endswith("_precision"):
                    continue
                class_name = key[: -len("_precision")]
                if class_name.lower() in self.class_mean_exclude:
                    continue
                try:
                    score = float(value)
                except Exception:
                    continue
                if not math.isfinite(score):
                    continue
                class_scores.append(score)

            if class_scores:
                class_mean = float(np.mean(np.array(class_scores, dtype=np.float64)))
                eval_results["bbox_mAP_class_mean"] = float(round(class_mean, 6))
            else:
                eval_results["bbox_mAP_class_mean"] = float("nan")

            return eval_results


def _set_coco_evaluator_cfg(
    evaluator_cfg: Any,
    ann_file: Path,
    class_mean_exclude: Sequence[str],
) -> None:
    if isinstance(evaluator_cfg, list):
        for item in evaluator_cfg:
            _set_coco_evaluator_cfg(item, ann_file, class_mean_exclude)
        return
    if not isinstance(evaluator_cfg, MutableMapping):
        return

    evaluator_cfg["type"] = "CocoMetricWithClassMean"
    evaluator_cfg["metric"] = "bbox"
    evaluator_cfg["ann_file"] = str(ann_file.resolve())
    evaluator_cfg["classwise"] = True
    evaluator_cfg["class_mean_exclude"] = list(class_mean_exclude)


def _register_epoch_augmentation_seed_hook() -> None:
    from mmengine.hooks import Hook
    from mmengine.registry import HOOKS

    @HOOKS.register_module(force=True)
    class EpochAugmentationSeedHook(Hook):  # type: ignore[misc]
        """
        RF-DETR-like behavior: reseed RNG at every epoch start so augmentation
        sampling changes epoch by epoch.
        """

        def __init__(self, base_seed: int = 42) -> None:
            self.base_seed = int(base_seed)

        def before_train_epoch(self, runner) -> None:
            import torch

            epoch = int(getattr(runner, "epoch", 0))
            epoch_seed = self.base_seed + epoch
            random.seed(epoch_seed)
            np.random.seed(epoch_seed % (2**32 - 1))
            torch.manual_seed(epoch_seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(epoch_seed)
            if getattr(runner, "logger", None) is not None:
                runner.logger.info(f"[AugmentSeed] epoch={epoch + 1:03d} seed={epoch_seed}")


def query_gpu_status_with_nvidia_smi() -> List[Dict[str, float]]:
    cmd = [
        "nvidia-smi",
        "--query-gpu=index,utilization.gpu,memory.used,memory.total",
        "--format=csv,noheader,nounits",
    ]
    proc = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    rows: List[Dict[str, float]] = []
    for raw in proc.stdout.strip().splitlines():
        parts = [p.strip() for p in raw.split(",")]
        if len(parts) != 4:
            continue
        gpu_idx = int(parts[0])
        util_pct = float(parts[1])
        mem_used = float(parts[2])
        mem_total = float(parts[3])
        mem_pct = 100.0 * mem_used / mem_total if mem_total > 0 else 100.0
        score = util_pct * 0.7 + mem_pct * 0.3
        rows.append(
            {
                "index": float(gpu_idx),
                "util_pct": util_pct,
                "mem_used_mb": mem_used,
                "mem_total_mb": mem_total,
                "mem_pct": mem_pct,
                "score": score,
            }
        )
    if not rows:
        raise RuntimeError("No GPU rows parsed from nvidia-smi output.")
    return rows


def pick_gpu_index(args: argparse.Namespace) -> int | None:
    # Manual override always wins.
    if args.gpu_id is not None:
        return int(args.gpu_id)

    excluded = {int(x) for x in args.exclude_gpus}

    try:
        rows = query_gpu_status_with_nvidia_smi()
    except Exception as exc:
        print(
            "Warning: GPU auto-selection via nvidia-smi failed. "
            f"Falling back to default GPU. Reason: {exc}"
        )
        return None

    candidates = [r for r in rows if int(r["index"]) not in excluded]
    if not candidates:
        print(
            "Warning: all GPUs were excluded from auto selection. "
            "Falling back to default GPU."
        )
        return None

    best = min(
        candidates,
        key=lambda r: (r["score"], r["util_pct"], r["mem_pct"], r["index"]),
    )
    print("GPU status (lower score is better):")
    for r in sorted(rows, key=lambda x: int(x["index"])):
        mark = "*" if int(r["index"]) == int(best["index"]) else " "
        print(
            f"{mark} GPU {int(r['index'])}: util={r['util_pct']:.1f}% "
            f"mem={r['mem_used_mb']:.0f}/{r['mem_total_mb']:.0f}MB ({r['mem_pct']:.1f}%) "
            f"score={r['score']:.2f}"
        )
    return int(best["index"])


def main() -> None:
    args = parse_args()

    dataset_dir = args.dataset_dir.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    ensure_dataset_layout(dataset_dir)

    include_tokens = parse_class_tokens(args.include_classes)
    exclude_tokens = parse_class_tokens(args.exclude_classes)
    class_mean_exclude_tokens = parse_class_tokens(args.class_mean_exclude)
    use_augment = not args.disable_augment
    albu_train_transforms = build_rfdetr_style_albu_transforms() if use_augment else None
    filtered_dataset_dir, class_names = prepare_dataset_for_class_selection(
        source_dataset_dir=dataset_dir,
        output_dir=output_dir,
        include_tokens=include_tokens,
        exclude_tokens=exclude_tokens,
        overwrite_filtered=args.overwrite_filtered,
    )

    try:
        from mmengine.config import Config
        from mmengine.runner import Runner
        from mmdet.utils import register_all_modules
    except Exception as exc:
        raise ImportError(
            "Failed to import MMDetection/MMEngine.\n"
            "Please activate your rcnn environment and verify:\n"
            "  pip install -U mmengine mmcv mmdet"
        ) from exc

    register_all_modules(init_default_scope=True)
    _register_coco_metric_with_class_mean()
    _register_epoch_augmentation_seed_hook()

    if args.base_config:
        base_config_path = Path(args.base_config)
        if not base_config_path.exists():
            raise FileNotFoundError(f"--base-config not found: {base_config_path}")
    else:
        rel_path = MODEL_CANDIDATES[args.model]["config_rel_path"]
        base_config_path = find_mmdet_config_from_installed_package(rel_path)

    cfg = Config.fromfile(str(base_config_path))

    train_ann = filtered_dataset_dir / "train" / "_annotations.coco.json"
    valid_ann = filtered_dataset_dir / "valid" / "_annotations.coco.json"
    test_ann = filtered_dataset_dir / "test" / "_annotations.coco.json"
    train_img_dir = filtered_dataset_dir / "train"
    valid_img_dir = filtered_dataset_dir / "valid"
    test_img_dir = filtered_dataset_dir / "test"

    set_dataset_cfg(
        cfg=cfg.train_dataloader,
        ann_file=train_ann,
        img_dir=train_img_dir,
        classes=class_names,
        is_train=True,
        image_size=args.image_size,
        use_augment=use_augment,
        albu_transforms=albu_train_transforms,
    )
    set_dataset_cfg(
        cfg=cfg.val_dataloader,
        ann_file=valid_ann,
        img_dir=valid_img_dir,
        classes=class_names,
        is_train=False,
        image_size=args.image_size,
        use_augment=False,
        albu_transforms=None,
    )
    if test_ann.exists():
        set_dataset_cfg(
            cfg=cfg.test_dataloader,
            ann_file=test_ann,
            img_dir=test_img_dir,
            classes=class_names,
            is_train=False,
            image_size=args.image_size,
            use_augment=False,
            albu_transforms=None,
        )

    _set_coco_evaluator_cfg(
        evaluator_cfg=cfg.val_evaluator,
        ann_file=valid_ann,
        class_mean_exclude=class_mean_exclude_tokens,
    )
    if test_ann.exists():
        _set_coco_evaluator_cfg(
            evaluator_cfg=cfg.test_evaluator,
            ann_file=test_ann,
            class_mean_exclude=class_mean_exclude_tokens,
        )

    updated = recursively_set_num_classes(cfg.model, num_classes=len(class_names))
    anchor_updated = set_small_object_anchor_scales(cfg.model, scales=args.anchor_scales)

    cfg.train_dataloader["batch_size"] = int(args.batch_size)
    cfg.val_dataloader["batch_size"] = int(args.val_batch_size)
    cfg.test_dataloader["batch_size"] = int(args.val_batch_size)
    cfg.train_dataloader["num_workers"] = int(args.num_workers)
    cfg.val_dataloader["num_workers"] = int(args.num_workers)
    cfg.test_dataloader["num_workers"] = int(args.num_workers)
    # Force worker restart each epoch to refresh worker-side RNG states.
    # This helps keep epoch-wise augmentation variation explicit and stable.
    cfg.train_dataloader["persistent_workers"] = False if args.num_workers > 0 else False
    cfg.val_dataloader["persistent_workers"] = args.num_workers > 0
    cfg.test_dataloader["persistent_workers"] = args.num_workers > 0

    rescale_schedule(cfg, target_epochs=args.epochs)
    if args.lr is not None:
        cfg.optim_wrapper["optimizer"]["lr"] = float(args.lr)

    if args.amp and cfg.optim_wrapper.get("type", "") != "AmpOptimWrapper":
        cfg.optim_wrapper["type"] = "AmpOptimWrapper"
        cfg.optim_wrapper["loss_scale"] = "dynamic"

    checkpoint_hook = cfg.default_hooks.get("checkpoint", {})
    checkpoint_hook["type"] = "CheckpointHook"
    checkpoint_hook["interval"] = 1
    checkpoint_hook["max_keep_ckpts"] = int(args.max_keep_ckpts)
    checkpoint_hook["save_best"] = str(args.save_best_metric)
    checkpoint_hook["rule"] = "greater"
    checkpoint_hook["save_last"] = True
    cfg.default_hooks["checkpoint"] = checkpoint_hook

    custom_hooks = list(getattr(cfg, "custom_hooks", []))
    custom_hooks.append({"type": "EpochAugmentationSeedHook", "base_seed": int(args.seed)})
    cfg.custom_hooks = custom_hooks

    cfg.randomness = {"seed": int(args.seed), "deterministic": False}
    cfg.work_dir = str(output_dir)
    cfg.launcher = "none"

    if args.resume_from is not None:
        resume_path = args.resume_from.resolve()
        if not resume_path.exists():
            raise FileNotFoundError(f"--resume-from not found: {resume_path}")
        cfg.load_from = str(resume_path)
        cfg.resume = True
    elif args.load_from:
        cfg.load_from = args.load_from
        cfg.resume = False
    else:
        cfg.resume = False

    if args.test_only:
        cfg.load_from = resolve_checkpoint_for_test(args, output_dir)

    dumped_cfg_path = output_dir / "resolved_config.py"
    if use_augment and albu_train_transforms is not None:
        (output_dir / "augmentation_config.json").write_text(
            json.dumps(
                {
                    "policy": "rfdetr_style_albu",
                    "transforms": albu_train_transforms,
                    "epoch_seed_strategy": "base_seed + epoch",
                    "base_seed": int(args.seed),
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
    cfg.dump(str(dumped_cfg_path))

    print("=== MMDetection RCNN Training Setup ===")
    print(f"Model preset: {args.model}")
    print(f"Base config: {base_config_path}")
    print(f"Model paper: {MODEL_CANDIDATES[args.model]['paper']}")
    print(f"Model repo: {MODEL_CANDIDATES[args.model]['repo']}")
    print(f"Dataset dir (source): {dataset_dir}")
    print(f"Dataset dir (used):   {filtered_dataset_dir}")
    print(summarize_split(filtered_dataset_dir, "train"))
    print(summarize_split(filtered_dataset_dir, "valid"))
    print(summarize_split(filtered_dataset_dir, "test"))
    print(f"Classes ({len(class_names)}): {class_names}")
    print(f"num_classes fields updated: {updated}")
    print(f"small-object anchors updated: {anchor_updated} (scales={args.anchor_scales})")
    print(f"Resolved config saved: {dumped_cfg_path}")
    print(f"Output dir: {output_dir}")
    print(f"AMP: {args.amp}")
    print(f"Test-only: {args.test_only}")
    print(f"save_best_metric: {args.save_best_metric}")
    print(f"class_mean_exclude: {class_mean_exclude_tokens}")
    print(f"augmentation: {'enabled (RF-DETR style Albu)' if use_augment else 'disabled'}")

    selected_gpu = pick_gpu_index(args)
    if selected_gpu is not None:
        import torch

        if not torch.cuda.is_available():
            print("Warning: CUDA is not available. Training will run on CPU.")
        else:
            if selected_gpu < 0 or selected_gpu >= torch.cuda.device_count():
                raise ValueError(
                    f"Selected GPU index {selected_gpu} is out of range. "
                    f"Visible CUDA device count: {torch.cuda.device_count()}"
                )
            torch.cuda.set_device(selected_gpu)
            cfg.device = f"cuda:{selected_gpu}"
            print(f"Using GPU {selected_gpu} for this run.")

    runner = Runner.from_cfg(cfg)
    if args.test_only:
        print(f"Running test with checkpoint: {cfg.load_from}")
        runner.test()
        return

    runner.train()

    if args.test_after_train:
        test_cfg = cfg.copy()
        test_cfg.load_from = resolve_checkpoint_for_test(args, output_dir)
        print(f"Running post-train test with checkpoint: {test_cfg.load_from}")
        Runner.from_cfg(test_cfg).test()


if __name__ == "__main__":
    main()
